services:
  db:
    ports:
      - "5432:5432"
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: investors
      POSTGRES_DB: investors
    volumes:
      - investors-db-data:/var/lib/postgresql/data
    restart: always

    healthcheck:
      test: pg_isready -U investors -d investors
      interval: 2s
      timeout: 3s
      retries: 40

  db-migration:
    image: liquibase/liquibase:4.29.2
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./database:/liquibase/changelog/
    command:
      --search-path=/liquibase/changelog/ --changelog-file changelog.yml --username investors --password=password --url jdbc:postgresql://db:5432/investors update
  db-seed:
    build:
      context: database
    environment: &environment
      DB_URL: postgresql://investors:password@db/investors
      SEED_FILE: /database/seed.csv
    volumes:
      - ./database:/database/
    depends_on:
      db-migration:
        condition: service_completed_successfully
  backend:
    build:
      context: backend
    ports:
      - "8080:8080"
    environment:
      <<: *environment
    depends_on:
      db-seed:
        condition: service_completed_successfully

  frontend:
    build:
      context: frontend
    ports:
      - "3000:3000"
    environment:
      VITE_BACKEND_API_URL: http://localhost:8080
    depends_on:
      backend:
        condition: service_started

volumes:
  investors-db-data:
    name: investors-db-data
